CREATE OR REPLACE VIEW DKMH(ID,MONHOC,TINCHI,PHONGHOC,TOANHA,KY,NAM,KHOAVIEN)
AS SELECT SECTION.COURSE_ID, COURSE.TITLE, COURSE.CREDITS, SECTION.ROOM_NUMBER,
        SECTION.BUILDING, SECTION.SEMESTER, SECTION.YEAR, COURSE.DEPT_NAME
FROM COURSE , SECTION
WHERE COURSE.COURSE_ID = SECTION.COURSE_ID;
/
CREATE OR REPLACE VIEW KQMH(MASV,ID,MONHOC,TINCHI,KY,NAM,DIEM,KHOAVIEN)
AS SELECT TAKES.ID, COURSE.COURSE_ID, COURSE.TITLE, COURSE.CREDITS,
    TAKES.SEMESTER, TAKES.YEAR, TAKES.GRADE, COURSE.DEPT_NAME
FROM TAKES, COURSE
WHERE COURSE.COURSE_ID = TAKES.COURSE_ID;